version: "3.5"

services:
  bobc:
    image: bobc:latest
    container_name: bobc
    ports:
      - 8100:8100
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: 8KLg2VSke13sAMId6HNqk4Bq
      S3_ENDPOINT: minio:9000
      S3_USE_SSL: "false"
      API_KEY: # pass from host
    depends_on:
      - minio
      - postgres

  minio:
    # For localhost access (e.g. to download pre-signed objects), add the following to your /etc/hosts
    # 127.0.0.1       minio
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    command:
      - server
      - /data
      - --console-address
      - ":9001"

  postgres:
    image: postgres:11.2-alpine
    container_name: postgres
    restart: always
    tmpfs:
      - /var/lib/postgres/data
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "8KLg2VSke13sAMId6HNqk4Bq"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    command:
      - -c
      - wal_level=replica #log level: saves every needed info for a point-in-time recovery.
      - -c
      - max_wal_senders=3
      - -c
      - max_replication_slots=3
      - -c
      - hot_standby=on #read-only
      - -c
      - log_statement=all
      - -c
      - log_destination=stderr

  adminer:
    image: adminer:4.7
    container_name: adminer
    # restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
