version: "3.5"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    command:
      - server
      - /data
      - --console-address
      - ":9001"

  db:
    image: postgres:11.2-alpine
    container_name: postgres
    restart: always
    tmpfs:
      - /var/lib/postgres/data
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "8KLg2VSke13sAMId6HNqk4Bq"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    command:
      - -c
      - wal_level=replica #log level: saves every needed info for a point-in-time recovery.
      - -c
      - max_wal_senders=3
      - -c
      - max_replication_slots=3
      - -c
      - hot_standby=on #read-only
      - -c
      - log_statement=all
      - -c
      - log_destination=stderr

  adminer:
    image: adminer:4.7
    container_name: adminer
    # restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
